name: "Build & Push"
on:
  workflow_dispatch:
    inputs:
      build_nautilus:
        description: "Build Nautilus"
        type: boolean
      build_dolphin:
        description: "Build Dolphin"
        type: boolean
      build_thunar:
        description: "Build Thunar"
        type: boolean
      build_krusader:
        description: "Build Krusader"
        type: boolean
      image_tag_version:
        description: "Image tag versions (comma-separated)"
        required: true

jobs:
  format-matrix:
    runs-on: ubuntu-latest
    outputs:
      build-apps: ${{ env.BUILD_APPS }}
    steps:
      - name: Format build-apps matrix
        shell: python
        run: |
          import os, json
          apps = []
          if "${{ github.event.inputs.build_nautilus }}" == "true":
            apps.append("nautilus")
          if "${{ github.event.inputs.build_dolphin }}" == "true":
            apps.append("dolphin")
          if "${{ github.event.inputs.build_thunar }}" == "true":
            apps.append("thunar")
          if "${{ github.event.inputs.build_krusader }}" == "true":
            apps.append("krusader")
          print("Build apps:", apps)
          with open(os.getenv('GITHUB_ENV'), "a") as ghenv:
              ghenv.write(f"BUILD_APPS={json.dumps(apps)}")

  build-push:
    name: "[${{ matrix.app }}] Build & Push"
    runs-on: ubuntu-latest
    needs:
      - format-matrix
    env:
      IMAGE_TAG_BASE: "ghcr.io/david-lor/${{ matrix.app }}-gui"
      IMAGE_TAG_INTERNAL: "${{ matrix.app }}-gui"
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJSON(needs.format-matrix.outputs.build-apps)}}

    steps:
      # Setup
      - name: "Checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      # Registry login
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & Push
      - name: "Docker build"
        working-directory: ${{ matrix.app }}
        run: docker build . -t ${{ env.IMAGE_TAG_INTERNAL }}
      - name: "Docker push tags"
        run: |
          for image_tag_version in $(echo "${{ github.event.inputs.image_tag_version }}" | sed "s/,/ /g")
          do
            IMAGE_TAG_FULL="${{ env.IMAGE_TAG_BASE }}:$image_tag_version"
            echo "Tagging & Pushing image tag: $IMAGE_TAG_FULL"

            docker tag "${{ env.IMAGE_TAG_INTERNAL }}" "$IMAGE_TAG_FULL"
            docker push "$IMAGE_TAG_FULL"
          done
